server:
  port: 8080

hubspot:
  client-id: ${HUBSPOT_CLIENT_ID}
  client-secret: ${HUBSPOT_CLIENT_SECRET}
  redirect-uri: http://localhost:8080/oauth/callback
  token-url: https://api.hubapi.com/oauth/v1/token
  auth-url: https://app.hubspot.com/oauth/authorize
  api-url: https://api.hubapi.com
  scopes: ${HUBSPOT_SCOPES}

logging:
  level:
    root: INFO